SELECT *
FROM customer
LIMIT 20;

-- Business questions
-- Q1. What is the total revenue generated by male vs. female customers?
-- Q2. Which customers used a discount but still spent more than the average purchase amount?
-- Q3. Which are the top 5 products with the highest average review rating?
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
-- Q8. What are the top 3 most purchased products within each category?
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
-- Q10. What is the revenue contribution of each age group?

--------------
-- Business questions
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

WITH avg_adjusted AS (
SELECT
*,
AVG(purchase_amount) OVER() AS avg_purchase
FROM customer
)
SELECT customer_id, purchase_amount, discount_applied, avg_purchase
FROM avg_adjusted
WHERE discount_applied = 'Yes' AND purchase_amount > avg_purchase
;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating) :: numeric, 2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard', 'Express')
LIMIT 10;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
SELECT subscription_status, ROUND(AVG(purchase_amount), 2) AS avg_purchase, SUM(purchase_amount) AS total_purcase
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
WITH discount_adj AS (
SELECT
item_purchased,
CASE WHEN discount_applied = 'Yes' THEN 1.0
	ELSE 0 END AS discounted
FROM customer
)
SELECT item_purchased, ROUND((SUM(discounted)/COUNT(discounted) * 100), 2) AS percentage_discounted
FROM discount_adj
GROUP BY item_purchased
ORDER BY percentage_discounted DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.

WITH loyalty_adjusted AS (
SELECT customer_id, previous_purchases, 
CASE WHEN previous_purchases = 1.0 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10  THEN 'Returning'
	WHEN previous_purchases > 10.0 THEN 'Loyal' END AS customer_loyalty
FROM customer
)
SELECT customer_loyalty, COUNT(*) AS number_of_customers
FROM loyalty_adjusted
GROUP BY customer_loyalty
ORDER BY number_of_customers DESC;

-- Q8. What are the top 3 most purchased products within each category?
WITH count_adjusted AS (
SELECT category, item_purchased, COUNT(item_purchased) AS item_count
FROM customer
GROUP BY category, item_purchased
),
ranking_adjusted AS (
SELECT category, item_purchased, item_count, ROW_NUMBER() OVER(PARTITION BY category ORDER BY item_count DESC) AS category_item_ranking
FROM count_adjusted
)
SELECT category, item_purchased, item_count, category_item_ranking
FROM ranking_adjusted
WHERE category_item_ranking BETWEEN 1 AND 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
WITH repeat_adjusted AS (
SELECT previous_purchases, subscription_status, 
CASE WHEN subscription_status = 'Yes' THEN 1.0
	ELSE 0.0 END AS subscribed
FROM customer
WHERE previous_purchases > 5
)
SELECT subscription_status, COUNT(previous_purchases) AS subscription_count
FROM repeat_adjusted
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT *
FROM customer
LIMIT 5;

SELECT age_group, SUM(purchase_amount) AS revenue_contribution
FROM customer
GROUP BY age_group
ORDER BY revenue_contribution DESC;

